/**
 * 
 */
package com.gs.dbex.core.mssql;

/**
 * @author Sabuj Das
 *
 */
public final class SqlServerMetaQueryConstants {

	public static final String GET_ALL_TABLE_NAMSE = "SELECT * FROM INFORMATION_SCHEMA.TABLES";
	public static final String GET_ALL_TABLE_NAMES_BY_SCHEMA_SQL = "SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG=?";
	public static final String GET_ALL_COLUMNS_FOR_TABLE_QUERY = "SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_CATALOG=? AND TABLE_NAME=?";

	public static final String GET_TABLE_QUERY = "SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG=? AND TABLE_NAME=?";

	public static final String GET_TABLE_NAMES_SQL = "SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG LIKE ? AND TABLE_NAME LIKE ?";
	public static final String GET_TABLE_SQL = "SELECT * "
			+ "FROM INFORMATION_SCHEMA.TABLES T, INFORMATION_SCHEMA.COLUMNS C "
			+ "WHERE T.TABLE_CATALOG LIKE ? AND T.TABLE_NAME LIKE ? AND T.TABLE_NAME = C.TABLE_NAME AND T.TABLE_CATALOG = C.TABLE_CATALOG";

	public static final String GET_ALL_SCHEMA_NAMES_SQL = "SELECT * FROM INFORMATION_SCHEMA.SCHEMATA";

	public static final String GET_COLUMN_LIST_SQL = "SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_CATALOG = ? AND TABLE_NAME = ?";

	public static final String GET_ALL_CONSTRAINTS_SQL = "SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = ? AND TABLE_CATALOG = ? AND TABLE_NAME = ?";

}
