/**
 * 
 */
package com.gs.dbex.core.oracle;

/**
 * @author Sabuj Das
 * 
 */
public final class OracleMetaQueryConstants {

	public static final String AVAILABLE_SCHEMA_SQL = 
		"SELECT DISTINCT OWNER FROM ALL_CATALOG";

	public static final String ALL_TABLES_SQL = 
		"SELECT OWNER, TABLE_NAME, NUM_ROWS, TEMPORARY, DROPPED FROM ALL_TABLES WHERE OWNER = ?";

	public static final String ALL_COLUMNS_SQL = 
		"SELECT T.OWNER, T.TABLE_NAME, T.COLUMN_NAME, T.DATA_TYPE, " 
		+ "T.DATA_LENGTH, T.DATA_PRECISION, T.DATA_SCALE, T.NULLABLE, " 
		+ "T.COLUMN_ID, T.DEFAULT_LENGTH, T.DATA_DEFAULT, T.CHARACTER_SET_NAME, "
		+ " P.COMMENTS"  
		+ " FROM ALL_TAB_COLUMNS T, ALL_COL_COMMENTS P " 
		+ " WHERE "
		+ " T.OWNER=? " 
		+ " AND T.TABLE_NAME=? "
		+ " AND T.OWNER = P.OWNER " 
		+ " AND T.TABLE_NAME =P.TABLE_NAME " 
		+ " AND T.COLUMN_NAME = P.COLUMN_NAME ";

	public static final String GET_CONSTRAINT_COLUMNS_SQL = 
		"SELECT COLS.TABLE_NAME, COLS.COLUMN_NAME, CONS.STATUS, CONS.OWNER"
		+ " FROM ALL_CONSTRAINTS CONS, ALL_CONS_COLUMNS COLS"
		+ " WHERE "
		+ " CONS.CONSTRAINT_NAME = COLS.CONSTRAINT_NAME"
		+ " AND CONS.OWNER = COLS.OWNER"
		+ " AND CONS.TABLE_NAME = COLS.TABLE_NAME"
		+ " AND COLS.OWNER=?"
		+ " AND COLS.TABLE_NAME=?"
		+ " AND CONS.CONSTRAINT_TYPE = ?"
		+ " ORDER BY COLS.TABLE_NAME";
	
}
