/**
 * 
 */
package com.gs.dbex.application.constants;

/**
 * @author sabuj.das
 *
 */
public interface GuiCommandConstants {

	String _ACT_CMD = "";
	
	
	String NEW_CONNECTION_ACT_CMD 		= "NEW_CONNECTION_ACT_CMD";
	String NEW_CONN_W_CURR_ACT_CMD 		= "NEW_CONN_W_CURR_ACT_CMD";
	String DISCONN_DB__ACT_CMD 			= "DISCONN_DB__ACT_CMD";
	String DISCONN_ALL_DB__ACT_CMD 		= "DISCONN_ALL_DB__ACT_CMD";
	String NEW_QUERY_TAB_ACT_CMD 		= "NEW_QUERY_TAB_ACT_CMD";
	String OPEN_QUERY_FILE_ACT_CMD 		= "OPEN_QUERY_FILE_ACT_CMD";
	String OPEN_RESS_ACT_CMD 			= "OPEN_RESS_ACT_CMD";
	String TABLE_CONTENT_ACT_CMD 		= "TABLE_CONTENT_ACT_CMD";
	String TABLE_COLUMN_CONTENT_ACT_CMD	= "TABLE_COLUMN_CONTENT_ACT_CMD";
	String SAVE_QUERY_FILE_ACT_CMD 		= "SAVE_QUERY_FILE_ACT_CMD";
	String SAVE_AS_QUERY_FILE_ACT_CMD 	= "SAVE_AS_QUERY_FILE_ACT_CMD";
	String NEW_QUERY_BUILDER_ACT_CMD 	= "NEW_QUERY_BUILDER_ACT_CMD";
	String NEW_SCHEMA_DESIGNER_ACT_CMD 	= "NEW_SCHEMA_DESIGNER_ACT_CMD";
	String OPEN_RECENT_SQL_FILE_ACT_CMD = "OPEN_RECENT_SQL_FILE_ACT_CMD";
	String OPEN_RECENT_SCHEMA_D_ACT_CMD = "OPEN_RECENT_SCHEMA_D_ACT_CMD";
	
	String SAVE_CONNECTION_ACT_CMD 		= "SAVE_CONNECTION_ACT_CMD";
	String DELETE_CONNECTION_ACT_CMD 	= "DELETE_CONNECTION_ACT_CMD";
	String EDIT_CONNECTION_ACT_CMD 		= "EDIT_CONNECTION_ACT_CMD";
	String CANCEL_CONNECTION_ACT_CMD 	= "CANCEL_CONNECTION_ACT_CMD";
	String CREATE_CONNECTION_ACT_CMD 	= "CREATE_CONNECTION_ACT_CMD";
	String TEST_CONNECTION_ACT_CMD 		= "TEST_CONNECTION_ACT_CMD";
	
	String DB_SYNC_ACT_CMD 				= "DB_SYNC_ACT_CMD";
	String EXECUITE_CURRENT_SQL_ACT_CMD	= "EXECUITE_CURRENT_SQL_ACT_CMD";
	String REFRESH_DATABASE_ACT_CMD 	= "REFRESH_DATABASE_ACT_CMD";
	String BACKUP_DATABSE_ACT_CMD 		= "BACKUP_DATABSE_ACT_CMD";
	
	String EXIT_APP_ACT_CMD 			= "EXIT_APP_ACT_CMD";
	
	
	String COLLAPSE_PATH_ACTION 		= "COLLAPSE_PATH_ACTION";
    String EXPAND_PATH_ACTION 			= "EXPAND_PATH_ACTION";
    
    String VIEW_TABLE_DETAILS_ACT_CMD	= "VIEW_TABLE_DETAILS_ACT_CMD";
    
    String VIEW_BLOB_TEXT_ACT_CMD		= "VIEW_BLOB_TEXT_ACT_CMD";
    
    String SHOW_TOOLBAR_ACT_CMD 		= "SHOW_TOOLBAR_ACT_CMD";
	String SHOW_STATBAR_ACT_CMD 		= "SHOW_STATBAR_ACT_CMD";
	String SYS_LnF_ACT_CMD 				= "SYS_LnF_ACT_CMD";
	String METAL_ACT_CMD 				= "METAL_ACT_CMD";
	String OFFICE_2003_ACT_CMD 			= "OFFICE_2003_ACT_CMD";
	String OFFICE_XP_ACT_CMD 			= "OFFICE_XP_ACT_CMD";
	String FOREST_ACT_CMD 				= "FOREST_ACT_CMD";
	
	String CASCADE_ACT_CMD 				= "CASCADE_ACT_CMD";
	String TILES_2003_ACT_CMD 			= "TILES_2003_ACT_CMD";
	//String FOREST_ACT_CMD 				= "FOREST_ACT_CMD";
	String STYLE_CFG_ACT_CMD			= "STYLE_CFG_ACT_CMD";
	String SEARCH_ITEM_ACT_CMD 			= "SEARCH_ITEM_ACT_CMD";
	String SEARCH_TABLE_ACT_CMD 		= "SEARCH_TABLE_ACT_CMD";
	String SEARCH_COLUMN_ACT_CMD 		= "SEARCH_COLUMN_ACT_CMD";
	String SEARCH_DATA_ACT_CMD 			= "SEARCH_DATA_ACT_CMD";

}
