/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SqlQueryPanel.java
 *
 * Created on Sep 13, 2010, 8:39:12 PM
 */

package com.gs.mockup.dbex.sql;

import com.gs.mockup.dbex.TextLineNumber;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 *
 * @author Sabuj Das
 */
public class SqlQueryPanel extends javax.swing.JPanel {

    public static void main(String [] a){
        JFrame frame = new JFrame("Test");
        frame.setSize(600, 400);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().setLayout(new BorderLayout());
        SqlQueryPanel p = new SqlQueryPanel();
        frame.getContentPane().add(p, BorderLayout.CENTER);
        frame.setVisible(true);

    }

    private TextLineNumber textLineNumber;
    /** Creates new form SqlQueryPanel */
    public SqlQueryPanel() {
        JTextPane textPane = new JTextPane();
        JScrollPane scrollPane = new JScrollPane(textPane);
        textLineNumber = new TextLineNumber(textPane);
        scrollPane.setRowHeaderView( textLineNumber );
        initComponents();
        sqlQuerySplitPane.setTopComponent(scrollPane);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        queryToolBar = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        sqlQuerySplitPane = new javax.swing.JSplitPane();
        queryStatusPanel = new javax.swing.JPanel();
        rowCountLabel = new javax.swing.JLabel();
        rowCountResultLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        queryRunnerProgressBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        queryToolBar.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        queryToolBar.add(jButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(queryToolBar, gridBagConstraints);

        sqlQuerySplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(sqlQuerySplitPane, gridBagConstraints);

        queryStatusPanel.setMinimumSize(new java.awt.Dimension(641, 30));
        queryStatusPanel.setPreferredSize(new java.awt.Dimension(641, 30));
        queryStatusPanel.setLayout(new java.awt.GridBagLayout());

        rowCountLabel.setText("Row Count : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        queryStatusPanel.add(rowCountLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        queryStatusPanel.add(rowCountResultLabel, gridBagConstraints);

        messageLabel.setText("Message");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        queryStatusPanel.add(messageLabel, gridBagConstraints);

        queryRunnerProgressBar.setMaximumSize(new java.awt.Dimension(150, 19));
        queryRunnerProgressBar.setMinimumSize(new java.awt.Dimension(150, 19));
        queryRunnerProgressBar.setPreferredSize(new java.awt.Dimension(150, 19));
        queryRunnerProgressBar.setString("Query Runner ...");
        queryRunnerProgressBar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        queryStatusPanel.add(queryRunnerProgressBar, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("|");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        queryStatusPanel.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(queryStatusPanel, gridBagConstraints);
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JProgressBar queryRunnerProgressBar;
    private javax.swing.JPanel queryStatusPanel;
    private javax.swing.JToolBar queryToolBar;
    private javax.swing.JLabel rowCountLabel;
    private javax.swing.JLabel rowCountResultLabel;
    private javax.swing.JSplitPane sqlQuerySplitPane;
    // End of variables declaration

}
