/**
 *
 */
package com.gs.dbex.launcher.splash;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 * @author Sabuj Das
 *
 */
public class DbexSplashPanel extends JPanel {

	private Image backgroundImage;
    
    /**
     * Creates new form NewDbexSplashPanel
     */
    public DbexSplashPanel() {
        ImageIcon imageIcon = new ImageIcon(
                getClass().getResource("/images/dbex-splash-background.png")
                );
        backgroundImage = imageIcon.getImage();
        Dimension size = new Dimension(backgroundImage.getWidth(null), 
                backgroundImage.getHeight(null));
        setPreferredSize(size);
        setMinimumSize(size);
        setMaximumSize(size);
        setSize(size);
        initComponents();
    }

    public void setProgressValue(int v){
    	splashProgressBar.setValue(v);
    	updateUI();
    }

    public void setProgressMessage(String message){
    	splashMessageLabel.setText(message);
    	updateUI();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        versionLabel = new javax.swing.JLabel();
        splashMessageLabel = new javax.swing.JLabel();
        copyRightLabel = new javax.swing.JLabel();
        splashProgressBar = new javax.swing.JProgressBar();
        backgroundLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        versionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(204, 255, 204));
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        versionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Helium.png"))); // NOI18N
        add(versionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 90, 30));

        splashMessageLabel.setText("Starting Database Explorer...");
        add(splashMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 510, -1));

        copyRightLabel.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        copyRightLabel.setForeground(new java.awt.Color(255, 255, 255));
        copyRightLabel.setText("<html>\n<body>\n<b>D</b>atabase <b>E</b>xplorer (DbEx) is a free tool for multiple database management. " +
        		"Created and managed by Sabuj Das.<br/>\nPlease visit " +
        		"http://code.google.com/p/database-explorer for more information.\n</body>\n</html>");
        add(copyRightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, 510, 30));

        splashProgressBar.setBackground(new Color(67, 109, 209));
        splashProgressBar.setForeground(new Color(40, 210, 43));
        splashProgressBar.setValue(0);
        splashProgressBar.setBorderPainted(false);
        splashProgressBar.setDoubleBuffered(true);
        splashProgressBar.setFocusable(false);
        add(splashProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 249, 510, 10));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dbex-splash-background.png"))); // NOI18N
        add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 300));
    }// </editor-fold>
    // Variables declaration - do not modify
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel copyRightLabel;
    private javax.swing.JLabel splashMessageLabel;
    private javax.swing.JProgressBar splashProgressBar;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration
}
